"""Ground-truth world knowledge tables for Simply's curriculum.

Every entry here is a plain fact, stored once, so the training loop can
generate lesson after lesson that is correct by construction. Only
characters that exist in Simply's fixed charset (letters, digits, space,
! ' , - . : ?) are used. Uppercase "X" is absent from the charset, so
words/symbols containing it (Xe, Xenon) are excluded on purpose.
"""

# --- country capitals (full set, ASCII spellings) ------------------------
CAPITALS = {
    "Afghanistan": "Kabul", "Albania": "Tirana", "Algeria": "Algiers",
    "Andorra": "Andorra la Vella", "Angola": "Luanda",
    "Antigua and Barbuda": "Saint John's", "Argentina": "Buenos Aires",
    "Armenia": "Yerevan", "Australia": "Canberra", "Austria": "Vienna",
    "Azerbaijan": "Baku", "the Bahamas": "Nassau", "Bahrain": "Manama",
    "Bangladesh": "Dhaka", "Barbados": "Bridgetown", "Belarus": "Minsk",
    "Belgium": "Brussels", "Belize": "Belmopan", "Benin": "Porto-Novo",
    "Bhutan": "Thimphu", "Bolivia": "La Paz",
    "Bosnia and Herzegovina": "Sarajevo", "Botswana": "Gaborone",
    "Brazil": "Brasilia", "Brunei": "Bandar Seri Begawan",
    "Bulgaria": "Sofia", "Burkina Faso": "Ouagadougou", "Burundi": "Gitega",
    "Cambodia": "Phnom Penh", "Cameroon": "Yaounde", "Canada": "Ottawa",
    "Cape Verde": "Praia", "the Central African Republic": "Bangui",
    "Chad": "N'Djamena", "Chile": "Santiago", "China": "Beijing",
    "Colombia": "Bogota", "the Comoros": "Moroni",
    "the Republic of the Congo": "Brazzaville", "Costa Rica": "San Jose",
    "Croatia": "Zagreb", "Cuba": "Havana", "Cyprus": "Nicosia",
    "the Czech Republic": "Prague", "Denmark": "Copenhagen",
    "Djibouti": "Djibouti", "Dominica": "Roseau",
    "the Dominican Republic": "Santo Domingo", "Ecuador": "Quito",
    "Egypt": "Cairo", "El Salvador": "San Salvador",
    "Equatorial Guinea": "Malabo", "Eritrea": "Asmara", "Estonia": "Tallinn",
    "Eswatini": "Mbabane", "Ethiopia": "Addis Ababa", "Fiji": "Suva",
    "Finland": "Helsinki", "France": "Paris", "Gabon": "Libreville",
    "Gambia": "Banjul", "Georgia": "Tbilisi", "Germany": "Berlin",
    "Ghana": "Accra", "Greece": "Athens", "Grenada": "Saint George's",
    "Guatemala": "Guatemala City", "Guinea": "Conakry",
    "Guinea-Bissau": "Bissau", "Guyana": "Georgetown", "Haiti": "Port-au-Prince",
    "Honduras": "Tegucigalpa", "Hungary": "Budapest", "Iceland": "Reykjavik",
    "India": "New Delhi", "Indonesia": "Jakarta", "Iran": "Tehran",
    "Iraq": "Baghdad", "Ireland": "Dublin", "Israel": "Jerusalem",
    "Italy": "Rome", "Jamaica": "Kingston", "Japan": "Tokyo",
    "Jordan": "Amman", "Kazakhstan": "Astana", "Kenya": "Nairobi",
    "Kiribati": "Tarawa", "Kuwait": "Kuwait City", "Kyrgyzstan": "Bishkek",
    "Laos": "Vientiane", "Latvia": "Riga", "Lebanon": "Beirut",
    "Lesotho": "Maseru", "Liberia": "Monrovia", "Libya": "Tripoli",
    "Liechtenstein": "Vaduz", "Lithuania": "Vilnius",
    "Luxembourg": "Luxembourg", "Madagascar": "Antananarivo",
    "Malawi": "Lilongwe", "Malaysia": "Kuala Lumpur", "the Maldives": "Male",
    "Mali": "Bamako", "Malta": "Valletta", "the Marshall Islands": "Majuro",
    "Mauritania": "Nouakchott", "Mauritius": "Port Louis",
    "Mexico": "Mexico City", "Micronesia": "Palikir", "Moldova": "Chisinau",
    "Monaco": "Monaco", "Mongolia": "Ulaanbaatar", "Montenegro": "Podgorica",
    "Morocco": "Rabat", "Mozambique": "Maputo", "Myanmar": "Naypyidaw",
    "Namibia": "Windhoek", "Nauru": "Yaren", "Nepal": "Kathmandu",
    "the Netherlands": "Amsterdam", "New Zealand": "Wellington",
    "Nicaragua": "Managua", "Niger": "Niamey", "Nigeria": "Abuja",
    "North Korea": "Pyongyang", "North Macedonia": "Skopje", "Norway": "Oslo",
    "Oman": "Muscat", "Pakistan": "Islamabad", "Palau": "Ngerulmud",
    "Panama": "Panama City", "Papua New Guinea": "Port Moresby",
    "Paraguay": "Asuncion", "Peru": "Lima", "the Philippines": "Manila",
    "Poland": "Warsaw", "Portugal": "Lisbon", "Qatar": "Doha",
    "Romania": "Bucharest", "Russia": "Moscow", "Rwanda": "Kigali",
    "Saint Kitts and Nevis": "Basseterre", "Saint Lucia": "Castries",
    "Saint Vincent and the Grenadines": "Kingstown", "Samoa": "Apia",
    "San Marino": "San Marino", "Sao Tome and Principe": "Sao Tome",
    "Saudi Arabia": "Riyadh", "Senegal": "Dakar", "Serbia": "Belgrade",
    "the Seychelles": "Victoria", "Sierra Leone": "Freetown",
    "Singapore": "Singapore", "Slovakia": "Bratislava",
    "Slovenia": "Ljubljana", "the Solomon Islands": "Honiara",
    "Somalia": "Mogadishu", "South Africa": "Pretoria",
    "South Korea": "Seoul", "South Sudan": "Juba", "Spain": "Madrid",
    "Sri Lanka": "Colombo", "Sudan": "Khartoum", "Suriname": "Paramaribo",
    "Sweden": "Stockholm", "Switzerland": "Bern", "Syria": "Damascus",
    "Taiwan": "Taipei", "Tajikistan": "Dushanbe", "Tanzania": "Dodoma",
    "Thailand": "Bangkok", "Togo": "Lome", "Tonga": "Nuku'alofa",
    "Trinidad and Tobago": "Port of Spain", "Tunisia": "Tunis",
    "Turkey": "Ankara", "Turkmenistan": "Ashgabat", "Tuvalu": "Funafuti",
    "Uganda": "Kampala", "Ukraine": "Kyiv",
    "the United Arab Emirates": "Abu Dhabi",
    "the United Kingdom": "London", "the United States": "Washington, D.C.",
    "Uruguay": "Montevideo", "Uzbekistan": "Tashkent", "Vanuatu": "Port Vila",
    "Vatican City": "Vatican City", "Venezuela": "Caracas",
    "Vietnam": "Hanoi", "Yemen": "Sanaa", "Zambia": "Lusaka",
    "Zimbabwe": "Harare",
}

# --- currencies -----------------------------------------------------------
CURRENCIES = {
    "Afghanistan": "afghani", "Algeria": "dinar", "Argentina": "peso",
    "Armenia": "dram", "Australia": "dollar", "Austria": "euro",
    "Azerbaijan": "manat", "the Bahamas": "dollar", "Bahrain": "dinar",
    "Bangladesh": "taka", "Barbados": "dollar", "Belarus": "ruble",
    "Belgium": "euro", "Bolivia": "boliviano",
    "Bosnia and Herzegovina": "mark", "Botswana": "pula", "Brazil": "real",
    "Bulgaria": "lev", "Cambodia": "riel", "Cameroon": "franc",
    "Canada": "dollar", "Chile": "peso", "China": "yuan",
    "Colombia": "peso", "Costa Rica": "colon", "Croatia": "euro",
    "Cuba": "peso", "Cyprus": "euro", "the Czech Republic": "koruna",
    "Denmark": "krone", "the Dominican Republic": "peso", "Ecuador": "dollar",
    "Egypt": "pound", "Estonia": "euro", "Ethiopia": "birr", "Fiji": "dollar",
    "Finland": "euro", "France": "euro", "Gambia": "dalasi",
    "Georgia": "lari", "Germany": "euro", "Ghana": "cedi", "Greece": "euro",
    "Guatemala": "quetzal", "Honduras": "lempira", "Hungary": "forint",
    "Iceland": "krona", "India": "rupee", "Indonesia": "rupiah",
    "Iran": "rial", "Iraq": "dinar", "Ireland": "euro", "Israel": "shekel",
    "Italy": "euro", "Jamaica": "dollar", "Japan": "yen", "Jordan": "dinar",
    "Kazakhstan": "tenge", "Kenya": "shilling", "Kuwait": "dinar",
    "Kyrgyzstan": "som", "Laos": "kip", "Latvia": "euro", "Lebanon": "pound",
    "Libya": "dinar", "Lithuania": "euro", "Malaysia": "ringgit",
    "Malta": "euro", "Mauritius": "rupee", "Mexico": "peso",
    "Mongolia": "tugrik", "Morocco": "dirham", "Mozambique": "metical",
    "Myanmar": "kyat", "Nepal": "rupee", "the Netherlands": "euro",
    "New Zealand": "dollar", "Nicaragua": "cordoba", "Niger": "franc",
    "Nigeria": "naira", "North Korea": "won", "Norway": "krone", "Oman": "rial",
    "Pakistan": "rupee", "Panama": "balboa", "Papua New Guinea": "kina",
    "Paraguay": "guarani", "Peru": "sol", "the Philippines": "peso",
    "Poland": "zloty", "Portugal": "euro", "Qatar": "riyal",
    "Romania": "leu", "Russia": "ruble", "Rwanda": "franc",
    "Saudi Arabia": "riyal", "Senegal": "franc", "Serbia": "dinar",
    "Singapore": "dollar", "Slovakia": "euro", "Slovenia": "euro",
    "Somalia": "shilling", "South Africa": "rand", "South Korea": "won",
    "Spain": "euro", "Sri Lanka": "rupee", "Sudan": "pound",
    "Sweden": "krona", "Switzerland": "franc", "Syria": "pound",
    "Taiwan": "dollar", "Tanzania": "shilling", "Thailand": "baht",
    "Tonga": "paanga", "Trinidad and Tobago": "dollar", "Tunisia": "dinar",
    "Turkey": "lira", "Turkmenistan": "manat", "Uganda": "shilling",
    "Ukraine": "hryvnia", "the United Arab Emirates": "dirham",
    "the United Kingdom": "pound", "the United States": "dollar",
    "Uruguay": "peso", "Uzbekistan": "som", "Venezuela": "bolivar",
    "Vietnam": "dong", "Zambia": "kwacha", "Zimbabwe": "dollar",
}

# --- continents -----------------------------------------------------------
CONTINENTS = {
    "Algeria": "Africa", "Angola": "Africa", "Benin": "Africa",
    "Botswana": "Africa", "Burkina Faso": "Africa", "Burundi": "Africa",
    "Cameroon": "Africa", "the Central African Republic": "Africa",
    "Chad": "Africa", "the Republic of the Congo": "Africa",
    "Egypt": "Africa", "Equatorial Guinea": "Africa", "Eritrea": "Africa",
    "Eswatini": "Africa", "Ethiopia": "Africa", "Gabon": "Africa",
    "Gambia": "Africa", "Ghana": "Africa", "Guinea": "Africa",
    "Kenya": "Africa", "Lesotho": "Africa", "Liberia": "Africa",
    "Libya": "Africa", "Madagascar": "Africa", "Malawi": "Africa",
    "Mali": "Africa", "Mauritania": "Africa", "Morocco": "Africa",
    "Mozambique": "Africa", "Namibia": "Africa", "Niger": "Africa",
    "Nigeria": "Africa", "Rwanda": "Africa", "Senegal": "Africa",
    "Sierra Leone": "Africa", "Somalia": "Africa", "South Africa": "Africa",
    "South Sudan": "Africa", "Sudan": "Africa", "Tanzania": "Africa",
    "Togo": "Africa", "Tunisia": "Africa", "Uganda": "Africa",
    "Zambia": "Africa", "Zimbabwe": "Africa",
    "Afghanistan": "Asia", "Armenia": "Asia", "Azerbaijan": "Asia",
    "Bahrain": "Asia", "Bangladesh": "Asia", "Bhutan": "Asia",
    "Cambodia": "Asia", "China": "Asia", "Cyprus": "Asia",
    "India": "Asia", "Indonesia": "Asia", "Iran": "Asia", "Iraq": "Asia",
    "Israel": "Asia", "Japan": "Asia", "Jordan": "Asia",
    "Kazakhstan": "Asia", "Kuwait": "Asia", "Kyrgyzstan": "Asia",
    "Laos": "Asia", "Lebanon": "Asia", "Malaysia": "Asia",
    "the Maldives": "Asia", "Mongolia": "Asia", "Myanmar": "Asia",
    "Nepal": "Asia", "North Korea": "Asia", "Oman": "Asia",
    "Pakistan": "Asia", "the Philippines": "Asia", "Qatar": "Asia",
    "Saudi Arabia": "Asia", "Singapore": "Asia", "South Korea": "Asia",
    "Sri Lanka": "Asia", "Syria": "Asia", "Taiwan": "Asia",
    "Tajikistan": "Asia", "Thailand": "Asia", "Turkey": "Asia",
    "Turkmenistan": "Asia", "the United Arab Emirates": "Asia",
    "Uzbekistan": "Asia", "Vietnam": "Asia", "Yemen": "Asia",
    "Albania": "Europe", "Andorra": "Europe", "Austria": "Europe",
    "Belarus": "Europe", "Belgium": "Europe",
    "Bosnia and Herzegovina": "Europe", "Bulgaria": "Europe",
    "Croatia": "Europe", "the Czech Republic": "Europe",
    "Denmark": "Europe", "Estonia": "Europe", "Finland": "Europe",
    "France": "Europe", "Germany": "Europe", "Greece": "Europe",
    "Hungary": "Europe", "Iceland": "Europe", "Ireland": "Europe",
    "Italy": "Europe", "Latvia": "Europe", "Liechtenstein": "Europe",
    "Lithuania": "Europe", "Luxembourg": "Europe", "Malta": "Europe",
    "Moldova": "Europe", "Monaco": "Europe", "Montenegro": "Europe",
    "the Netherlands": "Europe", "North Macedonia": "Europe",
    "Norway": "Europe", "Poland": "Europe", "Portugal": "Europe",
    "Romania": "Europe", "Russia": "Europe", "San Marino": "Europe",
    "Serbia": "Europe", "Slovakia": "Europe", "Slovenia": "Europe",
    "Spain": "Europe", "Sweden": "Europe", "Switzerland": "Europe",
    "Ukraine": "Europe", "the United Kingdom": "Europe",
    "Vatican City": "Europe",
    "Canada": "North America", "Cuba": "North America",
    "Jamaica": "North America", "Mexico": "North America",
    "the United States": "North America",
    "Argentina": "South America", "Bolivia": "South America",
    "Brazil": "South America", "Chile": "South America",
    "Colombia": "South America", "Ecuador": "South America",
    "Guyana": "South America", "Paraguay": "South America",
    "Peru": "South America", "Uruguay": "South America",
    "Venezuela": "South America",
    "Australia": "Australia", "Fiji": "Oceania", "Kiribati": "Oceania",
    "the Marshall Islands": "Oceania", "Micronesia": "Oceania",
    "Nauru": "Oceania", "New Zealand": "Oceania", "Palau": "Oceania",
    "Papua New Guinea": "Oceania", "Samoa": "Oceania",
    "the Solomon Islands": "Oceania", "Tonga": "Oceania",
    "Tuvalu": "Oceania", "Vanuatu": "Oceania",
}

# --- chemical elements (Xenon excluded: uppercase X not in charset) -------
ELEMENTS = [
    ("hydrogen", "H"), ("helium", "He"), ("lithium", "Li"),
    ("beryllium", "Be"), ("boron", "B"), ("carbon", "C"),
    ("nitrogen", "N"), ("oxygen", "O"), ("fluorine", "F"), ("neon", "Ne"),
    ("sodium", "Na"), ("magnesium", "Mg"), ("aluminium", "Al"),
    ("silicon", "Si"), ("phosphorus", "P"), ("sulfur", "S"),
    ("chlorine", "Cl"), ("argon", "Ar"), ("potassium", "K"),
    ("calcium", "Ca"), ("scandium", "Sc"), ("titanium", "Ti"),
    ("vanadium", "V"), ("chromium", "Cr"), ("manganese", "Mn"),
    ("iron", "Fe"), ("cobalt", "Co"), ("nickel", "Ni"), ("copper", "Cu"),
    ("zinc", "Zn"), ("gallium", "Ga"), ("germanium", "Ge"),
    ("arsenic", "As"), ("selenium", "Se"), ("bromine", "Br"),
    ("krypton", "Kr"), ("rubidium", "Rb"), ("strontium", "Sr"),
    ("yttrium", "Y"), ("zirconium", "Zr"), ("niobium", "Nb"),
    ("molybdenum", "Mo"), ("technetium", "Tc"), ("ruthenium", "Ru"),
    ("rhodium", "Rh"), ("palladium", "Pd"), ("silver", "Ag"),
    ("cadmium", "Cd"), ("indium", "In"), ("tin", "Sn"), ("antimony", "Sb"),
    ("tellurium", "Te"), ("iodine", "I"), ("cesium", "Cs"),
    ("barium", "Ba"), ("lanthanum", "La"), ("cerium", "Ce"),
    ("praseodymium", "Pr"), ("neodymium", "Nd"), ("promethium", "Pm"),
    ("samarium", "Sm"), ("europium", "Eu"), ("gadolinium", "Gd"),
    ("terbium", "Tb"), ("dysprosium", "Dy"), ("holmium", "Ho"),
    ("erbium", "Er"), ("thulium", "Tm"), ("ytterbium", "Yb"),
    ("lutetium", "Lu"), ("hafnium", "Hf"), ("tantalum", "Ta"),
    ("tungsten", "W"), ("rhenium", "Re"), ("osmium", "Os"),
    ("iridium", "Ir"), ("platinum", "Pt"), ("gold", "Au"),
    ("mercury", "Hg"), ("thallium", "Tl"), ("lead", "Pb"),
    ("bismuth", "Bi"), ("radon", "Rn"), ("radium", "Ra"),
    ("actinium", "Ac"), ("thorium", "Th"), ("uranium", "U"),
    ("plutonium", "Pu"), ("americium", "Am"),
]

# --- US state capitals -----------------------------------------------------
STATES = {
    "Alabama": "Montgomery", "Alaska": "Juneau", "Arizona": "Phoenix",
    "Arkansas": "Little Rock", "California": "Sacramento",
    "Colorado": "Denver", "Connecticut": "Hartford", "Delaware": "Dover",
    "Florida": "Tallahassee", "Georgia": "Atlanta", "Hawaii": "Honolulu",
    "Idaho": "Boise", "Illinois": "Springfield", "Indiana": "Indianapolis",
    "Iowa": "Des Moines", "Kansas": "Topeka", "Kentucky": "Frankfort",
    "Louisiana": "Baton Rouge", "Maine": "Augusta", "Maryland": "Annapolis",
    "Massachusetts": "Boston", "Michigan": "Lansing",
    "Minnesota": "Saint Paul", "Mississippi": "Jackson",
    "Missouri": "Jefferson City", "Montana": "Helena", "Nebraska": "Lincoln",
    "Nevada": "Carson City", "New Hampshire": "Concord",
    "New Jersey": "Trenton", "New Mexico": "Santa Fe", "New York": "Albany",
    "North Carolina": "Raleigh", "North Dakota": "Bismarck",
    "Ohio": "Columbus", "Oklahoma": "Oklahoma City", "Oregon": "Salem",
    "Pennsylvania": "Harrisburg", "Rhode Island": "Providence",
    "South Carolina": "Columbia", "South Dakota": "Pierre",
    "Tennessee": "Nashville", "Texas": "Austin",
    "Utah": "Salt Lake City", "Vermont": "Montpelier",
    "Virginia": "Richmond", "Washington": "Olympia",
    "West Virginia": "Charleston", "Wisconsin": "Madison",
    "Wyoming": "Cheyenne",
}

# --- planets ---------------------------------------------------------------
PLANETS = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn",
           "Uranus", "Neptune"]
ORDINALS = ["first", "second", "third", "fourth", "fifth", "sixth",
            "seventh", "eighth"]

# --- months ----------------------------------------------------------------
MONTH_DAYS = {
    "January": 31, "February": 28, "March": 31, "April": 30, "May": 31,
    "June": 30, "July": 31, "August": 31, "September": 30, "October": 31,
    "November": 30, "December": 31,
}

# --- unit conversions (canonical Q/A pairs) --------------------------------
UNITS = [
    ("How many seconds are in a minute?",
     "There are 60 seconds in a minute."),
    ("How many minutes are in an hour?",
     "There are 60 minutes in an hour."),
    ("How many hours are in a day?",
     "There are 24 hours in a day."),
    ("How many days are in a week?",
     "There are 7 days in a week."),
    ("How many weeks are in a year?",
     "There are 52 weeks in a year."),
    ("How many months are in a year?",
     "There are 12 months in a year."),
    ("How many days are in a year?",
     "There are 365 days in a year."),
    ("How many hours are in a week?",
     "There are 168 hours in a week."),
    ("How many centimeters are in a meter?",
     "There are 100 centimeters in a meter."),
    ("How many meters are in a kilometer?",
     "There are 1000 meters in a kilometer."),
    ("How many grams are in a kilogram?",
     "There are 1000 grams in a kilogram."),
    ("How many kilograms are in a metric ton?",
     "There are 1000 kilograms in a metric ton."),
    ("How many milliliters are in a liter?",
     "There are 1000 milliliters in a liter."),
    ("How many inches are in a foot?",
     "There are 12 inches in a foot."),
    ("How many feet are in a yard?",
     "There are 3 feet in a yard."),
]

# --- world records and science facts (canonical Q/A pairs) -----------------
RECORDS = [
    ("What is the tallest mountain on Earth?",
     "Mount Everest is the tallest mountain on Earth."),
    ("What is the longest river in the world?",
     "The Nile is the longest river in the world."),
    ("What is the biggest ocean?",
     "The Pacific is the biggest ocean."),
    ("What is the smallest ocean?",
     "The Arctic is the smallest ocean."),
    ("What is the biggest hot desert?",
     "The Sahara is the biggest hot desert."),
    ("What is the biggest country by area?",
     "Russia is the biggest country by area."),
    ("What is the most populous country?",
     "India is the most populous country."),
    ("What is the biggest planet?",
     "Jupiter is the biggest planet."),
    ("What is the closest planet to the sun?",
     "Mercury is the closest planet to the sun."),
    ("What is the farthest planet from the sun?",
     "Neptune is the farthest planet from the sun."),
    ("What is the hottest planet?",
     "Venus is the hottest planet."),
    ("What is the closest star to Earth?",
     "The sun is the closest star to Earth."),
    ("What is the biggest animal?",
     "The blue whale is the biggest animal."),
    ("What is the tallest animal?",
     "The giraffe is the tallest animal."),
    ("What is the fastest land animal?",
     "The cheetah is the fastest land animal."),
    ("What is the biggest rainforest?",
     "The Amazon is the biggest rainforest."),
    ("What is the deepest ocean trench?",
     "The Mariana Trench is the deepest ocean trench."),
    ("What is the largest lake?",
     "The Caspian Sea is the largest lake."),
    ("What is the deepest lake?",
     "Lake Baikal is the deepest lake."),
    ("What is the tallest waterfall?",
     "Angel Falls is the tallest waterfall."),
    ("What is the smallest country?",
     "Vatican City is the smallest country."),
    ("What is the most spoken language?",
     "English is the most spoken language."),
    ("What is the hardest natural substance?",
     "Diamond is the hardest natural substance."),
    ("What is the main gas in the air?",
     "Nitrogen is the main gas in the air."),
    ("What is the biggest bone in the human body?",
     "The femur is the biggest bone in the human body."),
    ("What is the largest island?",
     "Greenland is the largest island."),
    ("What is the longest mountain range?",
     "The Andes is the longest mountain range."),
    ("What is the largest country in South America?",
     "Brazil is the largest country in South America."),
    ("What is the boiling point of water?",
     "Water boils at 100 degrees Celsius."),
    ("What is the freezing point of water?",
     "Water freezes at 0 degrees Celsius."),
    ("How many continents are there?",
     "There are 7 continents."),
    ("How many oceans are there?",
     "There are 5 oceans."),
    ("How many planets are there?",
     "There are 8 planets."),
    ("How many colors are in a rainbow?",
     "There are 7 colors in a rainbow."),
    ("How many bones does an adult human have?",
     "An adult human has 206 bones."),
    ("How many sides does a triangle have?",
     "A triangle has 3 sides."),
    ("How many sides does a square have?",
     "A square has 4 sides."),
    ("How many legs does a spider have?",
     "A spider has 8 legs."),
    ("How many legs does an insect have?",
     "An insect has 6 legs."),
    ("How many strings does a guitar have?",
     "A guitar has 6 strings."),
    ("What organ pumps blood through the body?",
     "The heart pumps blood through the body."),
    ("What gas do plants take in from the air?",
     "Plants take in carbon dioxide from the air."),
    ("What force pulls objects toward the ground?",
     "Gravity pulls objects toward the ground."),
    ("What is the national bird of the United States?",
     "The bald eagle is the national bird of the United States."),
    ("What language do most people in Brazil speak?",
     "Most people in Brazil speak Portuguese."),
]
